default:
    just --list

# run build_runner to generate all needed code for app to work
codegen:
    dart run swagger_parser
    dart run build_runner build

# run app locally as a webpage
local:
    flutter run -d web-server

# clean generated code
clean:
    dart run build_runner clean

alias g := codegen
alias l := local
alias c := clean